#page title
page_title                                : Walk Daily - Bible Reading App                                        # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1643083018                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/us/app/walk-daily-bible-reading/id1643083018                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/app-icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Walk Daily - Bible Reading App                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Purposeful Bible Reading. Tools Included.

social_title                              : Walk Daily - Bible Reading App
social_url                                : https://walkdaily.app/
social_description                        : Purposeful Bible Reading. Tools Included.
social_image                              : assets/social-image.png

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

enable_mailing_list                       : false    # set to show mailing list
mailing_list_url                          : https://script.google.com/macros/s/AKfycbxyz6dZFzDvK6dhbQ4o29qzdPbH9tJeCUu4Q-DyhL0xAYGrqEWmOy6XkiL27MHfIKEZHQ/exec

# Information About Yourself
your_name                                 : Cody Rigney                                
your_link                                 : 
your_city                                 : Canton, Ohio                                
email_address                             : walkdailybiblereading@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Choose Your Reading Plan
    description                           : Many popular reading plans bundled, with more to come. Already started a plan? Pick up where you left off.
    fontawesome_icon_name                 : book
    
  - title                                 : Track Your Progress Through the Plan
    description                           : Check off readings you complete each day. Don't worry if you fall behind, the app will keep track.
    fontawesome_icon_name                 : list-check

  - title                                 : Progress Highlights
    description                           : View your daily reading streak, favorite hour to read, how many verses you've read in total, and more.
    fontawesome_icon_name                 : chart-line

  - title                                 : Daily Reminders
    description                           : The app can remind you to read each day. Pick a time of day that works for you.
    fontawesome_icon_name                 : bell

  - title                                 : Take Notes (Pro)
    description                           : Record insights as you read and refer back to them later.
    fontawesome_icon_name                 : note-sticky

  - title                                 : Share with a Friend
    description                           : Share what you've read with a friend or accountability partner. Optionally include your notes.
    fontawesome_icon_name                 : share-from-square

  - title                                 : iCloud Sync (Pro)
    description                           : Sync all of your data to iCloud and ensure all of your devices are in sync.
    fontawesome_icon_name                 : cloud
  
  - title                                 : Dark and Light Mode
    description                           : The App's appearance changes based on your system settings.
    fontawesome_icon_name                 : moon

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.3
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#02161C"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#F0F3F4"

link_color                                : "#16809E"
button_text_color                         : "#ffffff"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#16809E"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
